package ma.enset.noteservice;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import ma.enset.noteservice.model.NoteElement;
import ma.enset.noteservice.model.NoteModule;
import ma.enset.noteservice.repository.NoteElementRepository;
import ma.enset.noteservice.repository.NoteModuleRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Slf4j
@AllArgsConstructor
public class Seeder implements CommandLineRunner {

    private final NoteElementRepository noteElementRepository;
    private final NoteModuleRepository noteModuleRepository;

    @Override
    public void run(String... args) {

        List<NoteElement> noteElementSessionNormalS1S2 = List.of(
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
//------------------------- S2
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build()
        );

        List<NoteElement> noteElementSessionRattS1S2 = List.of(
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
//------------------------- S2
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(12.024f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(15.124f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(16.234f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(17.642f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
//--------------------------------------------------------------------------------------
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11116")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11126")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11216")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11226")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11316")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11326")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11416")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11426")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11516")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteElement.builder()
                        .note(5.542f)
                        .codeElement("TII11526")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build()
        );

        List<NoteModule> noteModulesSessionRatt = List.of(
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
                        .build(),
//------------------------- S2

                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session1")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session1")
                        .build()
        );

        List<NoteModule> noteModulesSessionNormal = List.of(
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII11006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII11006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII11006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII11006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII11006-session2")
                        .build(),
//------------------------- S2

                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(12.024f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-ahmed.elbouchouki-1-TII12006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(15.124f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-aymane.ouahmane-1-TII12006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(16.234f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-mohammed.benchelbikh-1-TII12006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(17.642f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-yacoub.benhamama-1-TII12006-session2")
                        .build(),
//-------------------------------
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11106")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11206")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11306")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11406")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build(),
                NoteModule.builder()
                        .note(5.542f)
                        .codeModule("TII11506")
                        .sessionId("2021-2023-zakaria.elmourtazak-1-TII12006-session2")
                        .build()
        );


//                        .idSession("2021-2023-ahmed.elbouchouki-1-TII11006-session1")
//                        .idSession("2021-2023-ahmed.elbouchouki-1-TII12006-session1")
//                        .idSession("2021-2023-aymane.ouahmane-1-TII11006-session1")
//                        .idSession("2021-2023-aymane.ouahmane-1-TII12006-session1")
//                        .idSession("2021-2023-mohammed.benchelbikh-1-TII11006-session1")
//                        .idSession("2021-2023-mohammed.benchelbikh-1-TII12006-session1")
//                        .idSession("2021-2023-yacoub.benhamama-1-TII11006-session1")
//                        .idSession("2021-2023-yacoub.benhamama-1-TII12006-session1")
//                        .idSession("2021-2023-zakaria.elmourtazak-1-TII11006-session1")
//                        .idSession("2021-2023-zakaria.elmourtazak-1-TII12006-session1")

        log.debug("Seeding NoteElement...");
        noteElementRepository.saveAll(noteElementSessionNormalS1S2);
        noteElementRepository.saveAll(noteElementSessionRattS1S2);
        log.debug("NoteElement seeded successfully.");

        log.debug("Seeding NoteModule...");
        noteModuleRepository.saveAll(noteModulesSessionNormal);
        noteModuleRepository.saveAll(noteModulesSessionRatt);
        log.debug("NoteModule seeded successfully.");
    }
}
