server:
  port: 50003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/module-db?useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: elbouchouki

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
