server:
    port: 50015

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/session-univ-db?useSSL=true&createDatabaseIfNotExist=true
        username: root
        password: elbouchouki

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: false

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

logging:
    level:
        org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
