server:
    port:

spring:
    application:
        name: note-service

    banner:
        location: classpath:banner.txt

    profiles:
        active: dev

    datasource:
        url:
        username:
        password:

    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        database-platform:

    messages:
        basename: messages.messages
        encoding: UTF-8

eureka:
    client:
        service-url:
            defaultZone: