server:
  port: 50009

spring:
  application:
    name: utilisateur-service

  datasource:
    url: jdbc:mysql://localhost:3306/utilisateur-db?useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: elbouchouki

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  messages:
    basename: messages.messages
    encoding: UTF-8

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true